language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  # need to upgrade pip for extras_require syntax on py2.7
  - 'pip install --upgrade pip'
  - 'pip install ".[test]"'
# command to run tests
script:
  - pytest
after_script:
  - flake8
